version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: java-postgres
    ports:
      - "45432:5432"
    expose:
      - 5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: TransportAgencyData
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
  app:
    image: transpor-agency:1.0-SNAPSHOT
    container_name: TransportAgency
    ports:
      - "8081:8080"
    environment:
      POSTGRES_HOST: postgres
    restart: always
    links:
      - postgres